# Generated by Django 4.2.11 on 2024-05-22 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0005_alter_usuario_password_alter_usuario_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='default_password_value', max_length=128),
        ),
    ]
